[global]
scanner = "$HOME/bin/fsscan"
tree = "$HOME/bin/cached-tree"
home_base = "/volume1/data/downloads/(music)"
trees_path = "{home_base}/catalogs/trees"
csvs_path = "{trees_path}/csv"
state_path = "{trees_path}/state"

[scan.laptop-music]
enabled = false
mode = "used"
disk = "/Users/ogd/Downloads/music"
desc = "laptop music directory"
header = "local music processing directory"

[scan.xphear]
enabled = false
mode = "subs"
disk = "/Volumes/XPHEAR"
desc = "XPHEAR (2TB blue Seagate Backup Plus)"
header = "2TB blue Seagate Backup Plus HD formatted with APFS (offline music archive)"

[scan.music-archives]
enabled = true
mode = "df"
disk = "/volume1/data/backups/atropos"
desc = "euterpe atropos (NAS directory)"
header = "2TB blue Seagate Backup Plus HD formatted with HFS+ (FLAC archive)"

[scan.television]
enabled = true
mode = "df"
disk = "/volume1/data/video/Television"
desc = "euterpe television (NAS directory)"
header = "Synology NAS //data/video/Television share"

[scan.movies]
enabled = true
mode = "df"
disk = "/volume1/data/video/Movies"
desc = "euterpe movies (NAS directory)"
header = "Synology NAS //data/video/Movies"

[scan.anime]
enabled = true
mode = "df"
disk = "/volume1/video/anime"
desc = "euterpe anime (NAS directory)"
header = "Synology NAS //video/anime"

[scan.music]
enabled = true
mode = "subs"
disk = "/volume1/music"
desc = "euterpe music (NAS volume)"
header = "Synology NAS //music"
